---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths:
  /:
    post:
     operationId: doOperation_topLevel
     parameters:
        - in: header
          name: notUsed
          schema: 
            type: string
          required: false
     requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MultiplicationOperation_topLevel'
     responses:
        "200":
          description: OK
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  product:
                    format: float
                    type: number
components:
  schemas:
    MultiplicationOperation_topLevel:
      type: object
      properties:
        leftElement:
          format: float
          type: number
        rightElement:
          format: float
          type: number